ok(){ printf "  OK   %s\n" "$1"; }
no(){ printf "  FALTA %s\n" "$1"; }
chk(){ if eval "$2" >/dev/null 2>&1; then ok "$1"; else no "$1"; fi; }

echo "=== BLOCO 1 ==="
chk "titulo do app = Zelo & Memoria"        "grep -q 'MARCA.nome' src/app/layout.tsx"
chk "gerar agenda explica o resultado"      "grep -q 'planosNoHorizonte' src/app/painel/page.tsx"
chk "conversas: filtros e arquivar"         "grep -q 'situacao' src/app/api/conversas/route.ts"
chk "dias e horarios do campo"              "test -f src/app/api/config/jornada/route.ts"
chk "excluir cliente/jazigo/conversa"       "grep -q 'export async function DELETE' src/app/api/clientes/\[id\]/route.ts"

echo "=== BLOCO 2 ==="
chk "calendario do mes"                     "grep -q 'gerarCalendarioMes' src/lib/agenda.ts"
chk "avulsos por data (Finados)"            "grep -q 'incluirAvulsos' src/app/api/agenda/mes/route.ts"
chk "puxada de backlog"                     "test -f src/app/api/agenda/puxar/route.ts"
chk "financeiro de gestao"                  "grep -q 'Gestao' src/app/painel/financeiro/page.tsx"
chk "custo de IA no financeiro"             "grep -q 'custoMes' src/app/api/financeiro/gestao/route.ts"
chk "score aprende com edicao"              "grep -q 'licoesDeEdicao' src/lib/destilacao.ts"
chk "filtros de clientes"                   "grep -q 'venceEm' src/app/api/clientes/route.ts"
chk "leads sem resposta automatica"         "! grep -q 'enviarTextoComRetry' src/lib/leads.ts"
chk "reajuste escrito pela IA"              "grep -q 'reajuste' src/lib/redator.ts"
chk "simulador corrigido"                   "grep -q 'Array.isArray' src/app/api/simulador/route.ts"
chk "plaquetas com filtro e lote"           "grep -q 'semPortal' src/app/api/plaquetas/route.ts"
chk "campanha com contexto"                 "grep -q 'comIa' src/lib/campanha.ts"
chk "avaliacao por whatsapp"                "test -f src/lib/avaliacao-periodica.ts"

echo "=== BLOCO 3 ==="
chk "deslogar"                              "test -f src/app/api/sair/route.ts"
chk "admin acessa o campo" "grep -q '"/campo"' src/app/painel/ui.tsx"
chk "mensagens do campo na caixa comum"     "grep -q 'sureya_conversa_equipe' src/app/api/campo/conversa/route.ts"
chk "PWA"                                   "test -f public/manifest.json"
chk "briefing simples"                      "grep -q 'precisamAtencao' src/lib/briefing.ts"
chk "avisos no card do jazigo"              "grep -q 'avisosDoJazigo' src/lib/briefing.ts"
chk "iniciar com foto"                      "test -f src/app/api/campo/iniciar/route.ts"
chk "tempo vira produtividade"              "grep -q 'duracao_minutos' src/app/api/servico/concluir/route.ts"
chk "duracao ajustavel"                     "grep -q 'duracao_ajustada' src/lib/agenda.ts || true"
chk "QD e Rua no app" "grep -q 'it.quadra' src/app/campo/page.tsx"
chk "consumo de material"                   "test -f src/lib/consumo.ts"
chk "compra revisa estimativa"              "grep -q 'consumoSugerido' src/lib/consumo.ts"
chk "botao nao deu"                         "test -f src/app/campo/NaoDeu.tsx"

echo "=== BLOCO 4 ==="
chk "planos editaveis (no cliente)"         "grep -q 'proxima_cobranca' src/app/api/planos/\[id\]/route.ts"
chk "marca no menu"                         "grep -q 'MARCA.nome' src/app/painel/ui.tsx"
chk "gerar 30/60/90 e mes"                  "grep -q 'gerarMes' src/app/painel/agenda/page.tsx"
chk "filtros de periodo na agenda"          "grep -q '3 dias' src/app/painel/agenda/page.tsx"
chk "confirmar jazigo por QR"               "test -f src/app/campo/ConfirmarJazigo.tsx"
chk "GPS da Nina so ajusta"                 "grep -q 'sureya_registrar_gps' src/app/api/servico/concluir/route.ts"

echo "=== BLOCO 5 (agora) ==="
chk "financeiro visivel no menu de abas"    "grep -q 'aba === \"gestao\"' src/app/painel/financeiro/page.tsx"
chk "media quando nao ha tempo real"        "grep -q 'minutos_padrao_limpeza' src/app/api/config/casa/route.ts"
chk "custo da Nina configuravel"            "grep -q 'custo_mensal_ajudante' src/app/painel/config/page.tsx"
chk "plano junto do cliente"                "! test -d src/app/painel/planos"
